### ISSUE TITLE
BL5000 Does not work with Neptune 3 Plus and Klipper. Does not obtain mesh after connection success.

### ISSUE THREAD

**Issue by RoguishlyHandsome** [sandmmakers/BedLeveler5000#30]
Printer: Neptune 3 Plus
FW: Klipper Ver: 0.12.0-1
Moonraker: 0.8.0-197
Host: Raspberry Pi 4. (aarch64, 32bit)
Version: v0.12.0-1-g74473322
OS: Raspbian GNU/Linux 11 (bullseye)
Distro: MainsailOS 1.2.1 (bullseye)

Issue: after creating Printer config, N3PLUS would home all axis, but then it would stop at obtaining Mesh. this also happens when using N4 MAX to connect to NP3 PLUS. 

Observed: Connection get established with BL5000 V0.3.0. Homing start. Homing is done. Acquiring mesh starts, and it gets stuck there. this can be reproduced with any other Moonraker based configuration. 

Steps taken to solve issue: Copy Json file for N4 MAX, and change the settings for the base points. No effect. 
copied Json from N3 Plus and changed the connection protocol from COM to Moonraker. No effect.

Hope this help solve the issue. 

[config-20231130-231145.zip](https://github.com/sandmmakers/BedLeveler5000/files/13520603/config-20231130-231145.zip)
![image](https://github.com/sandmmakers/BedLeveler5000/assets/152580872/616cc016-db20-452a-8535-ef16e4736263)
![image](https://github.com/sandmmakers/BedLeveler5000/assets/152580872/57ed11a6-3bb8-43e7-bde0-222563dd1be1)

**Comment by sandmmakers** [comment]
Thank you for the bug report. I've been working on enhancing BL5K's logging and testing capabilities and will work towards addressing this bug report this weekend.

**Comment by sandmmakers** [comment]
The `z_offset` field in the `probe` section of your `printer.cfg` is commented out. While BL5K currently doesn't (directly) use the `z_offset` value from the `probe` section, it does treat it as a required field (for error checking purposes) since the Klipper documentation states it is a required field. While you could test with the `z_offset` uncommented, I'm not sure the probe task would complete without a couple of source changes that I'm working on.

I'm currently working on bolstering BL5K's error detection, handling, and reporting capabilities. Once that is ready (possibly later today), I might need you to try BL5K again, but with logging turned on. Logging capabilities have been present since the initial version, but (currently) require command line options to enable.

**Comment by RoguishlyHandsome** [comment]
Happy to help.

**Comment by sandmmakers** [comment]
While I'm still finishing up the final items required for the next release (the new release will include improved error messages and error handling, plus a couple of minor bug fixes), I think I figured out why BL5K is not probing on your machine. Do you have a mesh loaded? BL5K's initialization sequence requires a loaded mesh so it can get the correct number of rows and columns. The new release will show a error message if it detects that no mesh is loaded and will then disconnect from the printer. A mesh is also required for Marlin 2 connections.

**Comment by sandmmakers** [comment]
Looks like a log is going to be needed to figure out what is happening. The new version should be ready later today.

**Comment by sandmmakers** [comment]
Also, did you add the `z_offset` field to your printer.cfg? The new version will not require it, but the current version does.

**Comment by sandmmakers** [comment]
I've finally been able to reproduce the probe error. It appears that the response from the printer with vanilla Klipper is different than with Elegoo's version of Klipper. The vanilla Klipper response doesn't include a few fields that the current version of BL5K uses. However, the new version no longer uses those fields, so it should resolve this issue. It wasn't until today that I've had access to vanilla Klipper.

**Comment by sandmmakers** [comment]
A new version of the Bed Leveler 5000 Software Suite has been released which should resolve this issue. If it doesn't, or there are any new issues, the documentation has been updated with steps to create a log file.

**Comment by sandmmakers** [comment]
When using the **Printer Info Wizard**, did you use the query feature or manually enter in the coordinates? Can you please provide the configuration file?

**Comment by sandmmakers** [comment]
I just noticed that the probe offset values in your `printer.cfg` do not match the values used by the official Marlin source. The values hard-coded into the Marlin firmware are -28.5, 22.

**Comment by sandmmakers** [comment]
I think the values for your `position_max` fields in the `stepper_x` and `stepper_y` sections of your `printer.cfg` might be incorrect. While you have a value of `320` for both, I think the correct value is `330`.

**Comment by RoguishlyHandsome** [comment]
> When using the **Printer Info Wizard**, did you use the query feature or manually enter in the coordinates? Can you please provide the configuration file?

Initially I thought that it might be an issue with the my cfg file, so I ran the Printwizard in conjunction with the screw leveling Gcode command for the six points on the bed. For every location hit by the Gcode, I clicked on the corresponding space in the wizard and ran a query to get the points registered by it. I repeated this over all six points to make sure that the numbers matched, and then created the JSON file. I used the newly created Json Printer and try to run the leveling and that is when I received the error shown on pic 2 above. As for the CFG file with the different bed size, no changes were made by me in this area. If I am not mistaken, this was the default size provided by the FeralEngineer printer.cfg setup. I will take a look at the default files at his repository and let you know if anything is different, or if I somehow made changes and completely forgot about it.

**Comment by sandmmakers** [comment]
Also, if you use `screws_tilt_adjust` you will get incorrect numbers when querying with the **Printer Info Wizard**. The `screws_tilt_adjust` feature places the probe over the area to sense, but the **Printer Info Wizard**'s query feature records the location of the nozzle. That means (assuming the `printer.cfg` is correct) the numbers recorded by **Printer Info Wizard** will have the probe offset applied twice, which is incorrect. The query feature was designed with the standard Elegoo Neptune 3/4 LCD controller's manual probe feature in mind. Using the LCD controller, pressing one of the manual leveling buttons places the nozzle, not the probe, over the location to be considered.

I will update the documentation to make that clear tonight and look into adding a "query probe" feature to **Printer Info Wizard**. I might just add a second button, so there would be a **Query Nozzle** button and a **Probe Probe** button. That would be trivial to implement since they would be the exact same thing, except one wouldn't apply the probe offset.

Thank you again for all of your help working on all of these issues!!!!!!!!

**Comment by RoguishlyHandsome** [comment]
I made changes to the Printer.cfg and added the 325 value for the X and Y steppers and lo and behold it completed the sequence just fine. The bed size on the cfg file was the main culprit for this. 

![image](https://github.com/sandmmakers/BedLeveler5000/assets/152580872/f1bd6bb4-2997-4249-96a4-167a348bd0b1)
