### ISSUE TITLE
MalwareBytes reports the InspectorG-code.exe file as malware

### ISSUE THREAD

**Issue by ShankboneCOS** [sandmmakers/BedLeveler5000#35]
The title says it all

**Comment by sandmmakers** [comment]
That is a false positive and is a know issue. PyInstaller is used to bundle the Python code into executables. Even though PyInstaller is a highly regarded utility used by hundreds of legitimate projects, a few bad apples have used it in the past to bundle malware. Since most anti-virus programs can't detect the actual virus, they flag any and all executables created with PyInstaller as a virus. Companies can get around this by buying a certificate, but the certificates are prohibitively expensive.

I've been looking into workarounds, but I might need to write my own custom Python code bundling utility to fully resolve it.

**Comment by sandmmakers** [comment]
Malwarebytes is not producing any false positives with release v0.4.0.

**Comment by jon-shanks-sapiens** [comment]
I'll have to check my version. I was still getting it reported as malware yesterday.

**Comment by sandmmakers** [comment]
I'm not sure how often Windows Defender's virus definitions normally update, but since BL5K was just white-listed yesterday morning I'm not surprised it is still getting flagged on some users machines. I'm guessing the updates are weekly. The other option is to manually update the definitions.

I installed the `mpam-fe.exe` updater available here: https://www.microsoft.com/en-us/wdsi/defenderupdates

![BL5K Microsoft white-listed 2023-12-30](https://github.com/sandmmakers/BedLeveler5000/assets/145303647/1f83f44c-3687-4d51-9600-449749e9652e)
