### ISSUE TITLE
flagged as containing MULTIPLE trojan malwares.

### ISSUE THREAD

**Issue by Thebytebeyond** [sandmmakers/BedLeveler5000#40]
Win Defender flags as malware. Wacatac, and multiple severe malwares

**Comment by sandmmakers** [comment]
Thank you for your interest in BL5K. These are false positives caused by overly aggressive and error-prone AI hueristics. In the past, some "script kiddies" used PyInstaller to bundle malware, and now, as a result, a number of anti-virus programs flag anything created with PyInstaller. Please updated your virus definitions.

![image](https://github.com/sandmmakers/BedLeveler5000/assets/145303647/e8fc342d-2676-4c6f-a92d-0088b081f063)

**Comment by sandmmakers** [comment]
Microsoft has white-listed release 0.4.0 for a second time: 
![image](https://github.com/sandmmakers/BedLeveler5000/assets/145303647/618d0003-50ad-44da-9fd2-1b973614e8f8)

**Comment by sandmmakers** [comment]
Microsoft has white listed release v0.4.0 for a second time. Hopefully, this time it actually works.
![image](https://github.com/sandmmakers/BedLeveler5000/assets/145303647/962c79a7-4286-4407-b6d8-7b8a8005ee38)

**Comment by sandmmakers** [comment]
With the latest set of Windows Defender virus definitions, no false positives are currently being observed.

**Comment by Thebytebeyond** [comment]
Win defender doesnt flag and malwarebytes doesnt flag. thanks for the hard work @sandmmakers

**Comment by sandmmakers** [comment]
Thank you for using BL5K!!
