### ISSUE TITLE
Error "Incorrect number of tokens in response..."  with IDEX printer.

### ISSUE THREAD

**Issue by john3volts3** [sandmmakers/BedLeveler5000#46]
Marlin 1.1.4 version on an Sovol SV04.
The message "Message: Incorrect number of tokens in response:" appear when trying to connect.   The Sovol SV04 reply temperature for Two tools T0 and T1. 

Response to a GetTemps in Printer Tester program.

Sent 'M105'
Error:
    Name: getTemperatures
    id_: getTemperatures0
    Context: {}
    Message: Incorrect number of tokens in response: [ok T0:245.00 /245.00 B:70.01 /70.00 T0:245.00 /245.00 T1:18.83 /0.00 @:58 B@:52 @0:58 @1:0].

Thank-you in advance.

**Comment by sandmmakers** [comment]
I just pushed a number of compatibility improvement changes.  While I haven't released a new version yet, you can download a build with the latest changes from here: https://github.com/sandmmakers/BedLeveler5000/actions/runs/7596074884.
Please note since I didn't send out false positive reports for this build, your anti-virus might flag it. Also, please note that the configuration file format has changed slightly to support a couple new features that are going to be included in the next release. I plan on uploading a video about the new features and release a new version within the next couple of days. However, if you get a chance to test the changes before that and let me know if they fix this issue, that would be very helpful. Thank you.
