### ISSUE TITLE
Neptune 4 Plus locations are off

### ISSUE THREAD

**Issue by massmans75** [sandmmakers/BedLeveler5000#59]
I love your program but having some issues using it on my Neptune 4 Plus printer.   All of the locations seem to be off by ~20mm on XY axis's.  

Photos can be found here and are sorted by date.  It starts with the homing during bed leveler connection.  In the screenshots of the printer, you can see the locations on the LCD do not match up to what Bed Leveler is following.  

https://photos.app.goo.gl/9YZKNUjpNownpAdm6

Attached is my printer.cfg file.  [printer.zip](https://github.com/sandmmakers/BedLeveler5000/files/14539019/printer.zip)

Thanks for your help,
Steve

**Comment by massmans75** [comment]
[printer.zip](https://github.com/sandmmakers/BedLeveler5000/files/14539026/printer.zip)

**Comment by sandmmakers** [comment]
From your pictures, BL5K appears to be working correctly. The manual/auxiliary leveling screen in the LCD controller moves nozzle to 7 specific locations, the center of the bed and each of the screw screw locations. BL5K moves the Z-probe sensor to those locations, instead of the nozzle since paper testing using the nozzle, while BL5K uses the Z-probe. The Z-probe is offset from the nozzle by x: -24.25mm and y: 20.45mm.

**Comment by massmans75** [comment]
I guess I didnt realize that the Z-probe isnt the nozzle.  I wasnt aware or just didnt understand that the probe is separate.  This is my first 3d printer with auto leveling.  Thanks for looking the pictures and verifying everything is working as designed.  

Thanks again for all your work on making BL5K and your YouTube channel.

**Comment by sandmmakers** [comment]
Not a problem and thank you! This stuff can be rather tricky.
