### ISSUE TITLE
Incorrect number of tokens in response error when probing

### ISSUE THREAD

**Issue by QuikSilver156** [sandmmakers/BedLeveler5000#63]
Attached log as requested thanks!
[log.txt](https://github.com/sandmmakers/BedLeveler5000/files/15284509/log.txt)

**Comment by QuikSilver156** [comment]
Information on printer
Ender 3 (original not pro, max, etc...)
Installed bltouch
glass bed
running marlin bugfix 2.1.x  2024-02-28

**Comment by sandmmakers** [comment]
Sorry, for not commenting earlier. Somehow I missed this ticket and only became aware of it now. I will look into the issue. Thank you for the log file!!

**Comment by sandmmakers** [comment]
I've been able to reproduce the issue in the Marlin Simulator so it shouldn't be too difficult to fix.

**Comment by QuikSilver156** [comment]
That's great news! Can't wait to try it out.

**Comment by sandmmakers** [comment]
I've actually already fixed the problem. The problem is/was occurring due to a bug in Marlin (the failing response line ending with `\r\n` instead of the correct `\n`) but I was able to add a workaround so BL5K now supports both line ending formats. Since I'm currently cleaning up a number of little issues in preparation for a new bug fix release, I haven't pushed the change to Github yet, but I will soon.
